GOVC_URL=https://10.146.58.28
DATASTORE=hyper12-datastore
SOURCE_IMAGE=ubuntu/ubuntu-24.04-autoinstall.iso
VM_NETWORK=VM Network
VM_CPU=2
VM_RAM_MB=4096
VM_DISK_GB=30
SECONDARY_NETWORK=Internal
CLIENT_PACKAGES=net-tools,curl,nginx
SERVER_PACKAGES=net-tools,curl,apache2
NUM_CLIENTS=1
NUM_SERVERS=1