vcenter_url="sjc-xc-vcenter.pdsjc.f5net.com"
datacenter="XC-DC"
cluster="SJC-XC-Cluster"
project="F5XC-Automation-Testing"
datastore="XC-PDatastore"
default_slo_network="VM-MGMT"
images_location="/var/lib/jenkins/vmware_images"
ovftool_binary="/usr/lib/ovftool_4.6/ovftool"
download_source="https://downloads.volterra.io/releases/rhel/9/x86_64/images/securemeshV2"
timeout=360